
title: Erie Outing Club
description: Erie Outing Club is a social Outdoor Club, we do bicycle riding, kayaking, hiking,backpacking, etc

url: "http://www.erieoutingclub.org/" # the base hostname & protocol for your site
baseurl: "/erieoutingclub.github.io" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown
highlighter: rouge

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

gems:
  - jekyll-sitemap
