
title: Erie Outing Club
description: Erie Outing Club is a social Outdoor Club, we do bicycle riding, kayaking, hiking,backpacking, etc

url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog



# Build settings
markdown: kramdown
highlighter: rouge

exclude: ["README.md", "LICENSE","CNAME", ".gitignore"]
